INSERT INTO districts VALUES('A0','Anantapur','AP0','Anantapur is a district of Andra Pradesh');
INSERT INTO districts VALUES('C1','Chittoor','AP0','Chittoor is a district of Andra Pradesh');
INSERT INTO districts VALUES('EG2','East Godavari','AP0','East Godavari is a district of Andra Pradesh');
INSERT INTO districts VALUES('G3','Guntur','AP0','Guntur is a district of Andra Pradesh');
INSERT INTO districts VALUES('K4','Kadapa','AP0','Kadapa is a district of Andra Pradesh');
INSERT INTO districts VALUES('K5','Krishna','AP0','Krishna is a district of Andra Pradesh');
INSERT INTO districts VALUES('K6','Kurnool','AP0','Kurnool is a district of Andra Pradesh');
INSERT INTO districts VALUES('P7','Prakasam','AP0','Prakasam is a district of Andra Pradesh');
INSERT INTO districts VALUES('N8','Nellore','AP0','Nellore is a district of Andra Pradesh');
INSERT INTO districts VALUES('S9','Srikakulam','AP0','Srikakulam is a district of Andra Pradesh');
INSERT INTO districts VALUES('V10','Visakhapatnam','AP0','Visakhapatnam is a district of Andra Pradesh');
INSERT INTO districts VALUES('V11','Vizianagaram','AP0','Vizianagaram is a district of Andra Pradesh');
INSERT INTO districts VALUES('WG12','West Godavari','AP0','West Godavari is a district of Andra Pradesh');
INSERT INTO districts VALUES('A13','Anjaw','AP1','Anjaw is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('C14','Changlang','AP1','Changlang is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('DV15','Dibang Valley','AP1','Dibang Valley is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('EK16','East Kameng','AP1','East Kameng is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('ES17','East Siang','AP1','East Siang is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('KD18','Kra Daadi','AP1','Kra Daadi is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('KK19','Kurung Kumey','AP1','Kurung Kumey is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('L20','Lohit','AP1','Lohit is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('L21','Longding','AP1','Longding is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('LDV22','Lower Dibang Valley','AP1','Lower Dibang Valley is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('LS23','Lower Subansiri','AP1','Lower Subansiri is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('N24','Namsai','AP1','Namsai is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('PP25','Papum Pare','AP1','Papum Pare is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('S26','Siang','AP1','Siang is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('T27','Tawang','AP1','Tawang is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('T28','Tirap','AP1','Tirap is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('US29','Upper Siang','AP1','Upper Siang is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('US30','Upper Subansiri','AP1','Upper Subansiri is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('WK31','West Kameng','AP1','West Kameng is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('WS32','West Siang','AP1','West Siang is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('I33','Itanagar','AP1','Itanagar is a district of Arunachal Pradesh');
INSERT INTO districts VALUES('B34','Baksa','A2','Baksa is a district of Assam');
INSERT INTO districts VALUES('B35','Barpeta','A2','Barpeta is a district of Assam');
INSERT INTO districts VALUES('B36','Biswanath','A2','Biswanath is a district of Assam');
INSERT INTO districts VALUES('B37','Bongaigaon','A2','Bongaigaon is a district of Assam');
INSERT INTO districts VALUES('C38','Cachar','A2','Cachar is a district of Assam');
INSERT INTO districts VALUES('C39','Charaideo','A2','Charaideo is a district of Assam');
INSERT INTO districts VALUES('C40','Chirang','A2','Chirang is a district of Assam');
INSERT INTO districts VALUES('D41','Darrang','A2','Darrang is a district of Assam');
INSERT INTO districts VALUES('D42','Dhemaji','A2','Dhemaji is a district of Assam');
INSERT INTO districts VALUES('D43','Dhubri','A2','Dhubri is a district of Assam');
INSERT INTO districts VALUES('D44','Dibrugarh','A2','Dibrugarh is a district of Assam');
INSERT INTO districts VALUES('G45','Goalpara','A2','Goalpara is a district of Assam');
INSERT INTO districts VALUES('G46','Golaghat','A2','Golaghat is a district of Assam');
INSERT INTO districts VALUES('H47','Hailakandi','A2','Hailakandi is a district of Assam');
INSERT INTO districts VALUES('H48','Hojai','A2','Hojai is a district of Assam');
INSERT INTO districts VALUES('J49','Jorhat','A2','Jorhat is a district of Assam');
INSERT INTO districts VALUES('KM50','Kamrup Metropolitan','A2','Kamrup Metropolitan is a district of Assam');
INSERT INTO districts VALUES('KR51','Kamrup (Rural)','A2','Kamrup (Rural) is a district of Assam');
INSERT INTO districts VALUES('KA52','Karbi Anglong','A2','Karbi Anglong is a district of Assam');
INSERT INTO districts VALUES('K53','Karimganj','A2','Karimganj is a district of Assam');
INSERT INTO districts VALUES('K54','Kokrajhar','A2','Kokrajhar is a district of Assam');
INSERT INTO districts VALUES('L55','Lakhimpur','A2','Lakhimpur is a district of Assam');
INSERT INTO districts VALUES('M56','Majuli','A2','Majuli is a district of Assam');
INSERT INTO districts VALUES('M57','Morigaon','A2','Morigaon is a district of Assam');
INSERT INTO districts VALUES('N58','Nagaon','A2','Nagaon is a district of Assam');
INSERT INTO districts VALUES('N59','Nalbari','A2','Nalbari is a district of Assam');
INSERT INTO districts VALUES('DH60','Dima Hasao','A2','Dima Hasao is a district of Assam');
INSERT INTO districts VALUES('S61','Sivasagar','A2','Sivasagar is a district of Assam');
INSERT INTO districts VALUES('S62','Sonitpur','A2','Sonitpur is a district of Assam');
INSERT INTO districts VALUES('SSM63','South Salmara Mankachar','A2','South Salmara Mankachar is a district of Assam');
INSERT INTO districts VALUES('T64','Tinsukia','A2','Tinsukia is a district of Assam');
INSERT INTO districts VALUES('U65','Udalguri','A2','Udalguri is a district of Assam');
INSERT INTO districts VALUES('WKA66','West Karbi Anglong','A2','West Karbi Anglong is a district of Assam');
INSERT INTO districts VALUES('A67','Araria','B3','Araria is a district of Bihar');
INSERT INTO districts VALUES('A68','Arwal','B3','Arwal is a district of Bihar');
INSERT INTO districts VALUES('A69','Aurangabad','B3','Aurangabad is a district of Bihar');
INSERT INTO districts VALUES('B70','Banka','B3','Banka is a district of Bihar');
INSERT INTO districts VALUES('B71','Begusarai','B3','Begusarai is a district of Bihar');
INSERT INTO districts VALUES('B72','Bhagalpur','B3','Bhagalpur is a district of Bihar');
INSERT INTO districts VALUES('B73','Bhojpur','B3','Bhojpur is a district of Bihar');
INSERT INTO districts VALUES('B74','Buxar','B3','Buxar is a district of Bihar');
INSERT INTO districts VALUES('D75','Darbhanga','B3','Darbhanga is a district of Bihar');
INSERT INTO districts VALUES('EC76','East Champaran','B3','East Champaran is a district of Bihar');
INSERT INTO districts VALUES('G77','Gaya','B3','Gaya is a district of Bihar');
INSERT INTO districts VALUES('G78','Gopalganj','B3','Gopalganj is a district of Bihar');
INSERT INTO districts VALUES('J79','Jamui','B3','Jamui is a district of Bihar');
INSERT INTO districts VALUES('J80','Jehanabad','B3','Jehanabad is a district of Bihar');
INSERT INTO districts VALUES('K81','Kaimur','B3','Kaimur is a district of Bihar');
INSERT INTO districts VALUES('K82','Katihar','B3','Katihar is a district of Bihar');
INSERT INTO districts VALUES('K83','Khagaria','B3','Khagaria is a district of Bihar');
INSERT INTO districts VALUES('K84','Kishanganj','B3','Kishanganj is a district of Bihar');
INSERT INTO districts VALUES('L85','Lakhisarai','B3','Lakhisarai is a district of Bihar');
INSERT INTO districts VALUES('M86','Madhepura','B3','Madhepura is a district of Bihar');
INSERT INTO districts VALUES('M87','Madhubani','B3','Madhubani is a district of Bihar');
INSERT INTO districts VALUES('M88','Munger','B3','Munger is a district of Bihar');
INSERT INTO districts VALUES('M89','Muzaffarpur','B3','Muzaffarpur is a district of Bihar');
INSERT INTO districts VALUES('N90','Nalanda','B3','Nalanda is a district of Bihar');
INSERT INTO districts VALUES('N91','Nawada','B3','Nawada is a district of Bihar');
INSERT INTO districts VALUES('P92','Patna','B3','Patna is a district of Bihar');
INSERT INTO districts VALUES('P93','Purnia','B3','Purnia is a district of Bihar');
INSERT INTO districts VALUES('R94','Rohtas','B3','Rohtas is a district of Bihar');
INSERT INTO districts VALUES('S95','Saharsa','B3','Saharsa is a district of Bihar');
INSERT INTO districts VALUES('S96','Samastipur','B3','Samastipur is a district of Bihar');
INSERT INTO districts VALUES('S97','Saran','B3','Saran is a district of Bihar');
INSERT INTO districts VALUES('S98','Sheikhpura','B3','Sheikhpura is a district of Bihar');
INSERT INTO districts VALUES('S99','Sheohar','B3','Sheohar is a district of Bihar');
INSERT INTO districts VALUES('S100','Sitamarhi','B3','Sitamarhi is a district of Bihar');
INSERT INTO districts VALUES('S101','Siwan','B3','Siwan is a district of Bihar');
INSERT INTO districts VALUES('S102','Supaul','B3','Supaul is a district of Bihar');
INSERT INTO districts VALUES('V103','Vaishali','B3','Vaishali is a district of Bihar');
INSERT INTO districts VALUES('WC104','West Champaran','B3','West Champaran is a district of Bihar');
INSERT INTO districts VALUES('B105','Balod','C4','Balod is a district of Chhattisgarh');
INSERT INTO districts VALUES('BB106','Baloda Bazar','C4','Baloda Bazar is a district of Chhattisgarh');
INSERT INTO districts VALUES('B107','Balrampur','C4','Balrampur is a district of Chhattisgarh');
INSERT INTO districts VALUES('B108','Bastar','C4','Bastar is a district of Chhattisgarh');
INSERT INTO districts VALUES('B109','Bemetara','C4','Bemetara is a district of Chhattisgarh');
INSERT INTO districts VALUES('B110','Bijapur','C4','Bijapur is a district of Chhattisgarh');
INSERT INTO districts VALUES('B111','Bilaspur','C4','Bilaspur is a district of Chhattisgarh');
INSERT INTO districts VALUES('D112','Dantewada','C4','Dantewada is a district of Chhattisgarh');
INSERT INTO districts VALUES('D113','Dhamtari','C4','Dhamtari is a district of Chhattisgarh');
INSERT INTO districts VALUES('D114','Durg','C4','Durg is a district of Chhattisgarh');
INSERT INTO districts VALUES('G115','Gariaband','C4','Gariaband is a district of Chhattisgarh');
INSERT INTO districts VALUES('JC116','Janjgir Champa','C4','Janjgir Champa is a district of Chhattisgarh');
INSERT INTO districts VALUES('J117','Jashpur','C4','Jashpur is a district of Chhattisgarh');
INSERT INTO districts VALUES('K118','Kabirdham','C4','Kabirdham is a district of Chhattisgarh');
INSERT INTO districts VALUES('K119','Kanker','C4','Kanker is a district of Chhattisgarh');
INSERT INTO districts VALUES('K120','Kondagaon','C4','Kondagaon is a district of Chhattisgarh');
INSERT INTO districts VALUES('K121','Korba','C4','Korba is a district of Chhattisgarh');
INSERT INTO districts VALUES('K122','Koriya','C4','Koriya is a district of Chhattisgarh');
INSERT INTO districts VALUES('M123','Mahasamund','C4','Mahasamund is a district of Chhattisgarh');
INSERT INTO districts VALUES('M124','Mungeli','C4','Mungeli is a district of Chhattisgarh');
INSERT INTO districts VALUES('N125','Narayanpur','C4','Narayanpur is a district of Chhattisgarh');
INSERT INTO districts VALUES('R126','Raigarh','C4','Raigarh is a district of Chhattisgarh');
INSERT INTO districts VALUES('R127','Raipur','C4','Raipur is a district of Chhattisgarh');
INSERT INTO districts VALUES('R128','Rajnandgaon','C4','Rajnandgaon is a district of Chhattisgarh');
INSERT INTO districts VALUES('S129','Sukma','C4','Sukma is a district of Chhattisgarh');
INSERT INTO districts VALUES('S130','Surajpur','C4','Surajpur is a district of Chhattisgarh');
INSERT INTO districts VALUES('S131','Surguja','C4','Surguja is a district of Chhattisgarh');
INSERT INTO districts VALUES('NG132','North Goa','G5','North Goa is a district of Goa');
INSERT INTO districts VALUES('SG133','South Goa','G5','South Goa is a district of Goa');
INSERT INTO districts VALUES('A134','Ahmedabad','G6','Ahmedabad is a district of Gujarat');
INSERT INTO districts VALUES('A135','Amreli','G6','Amreli is a district of Gujarat');
INSERT INTO districts VALUES('A136','Anand','G6','Anand is a district of Gujarat');
INSERT INTO districts VALUES('A137','Aravalli','G6','Aravalli is a district of Gujarat');
INSERT INTO districts VALUES('B138','Banaskantha','G6','Banaskantha is a district of Gujarat');
INSERT INTO districts VALUES('B139','Bharuch','G6','Bharuch is a district of Gujarat');
INSERT INTO districts VALUES('B140','Bhavnagar','G6','Bhavnagar is a district of Gujarat');
INSERT INTO districts VALUES('B141','Botad','G6','Botad is a district of Gujarat');
INSERT INTO districts VALUES('CU142','Chhota Udaipur','G6','Chhota Udaipur is a district of Gujarat');
INSERT INTO districts VALUES('D143','Dahod','G6','Dahod is a district of Gujarat');
INSERT INTO districts VALUES('D144','Dang','G6','Dang is a district of Gujarat');
INSERT INTO districts VALUES('DD145','Devbhoomi Dwarka','G6','Devbhoomi Dwarka is a district of Gujarat');
INSERT INTO districts VALUES('G146','Gandhinagar','G6','Gandhinagar is a district of Gujarat');
INSERT INTO districts VALUES('GS147','Gir Somnath','G6','Gir Somnath is a district of Gujarat');
INSERT INTO districts VALUES('J148','Jamnagar','G6','Jamnagar is a district of Gujarat');
INSERT INTO districts VALUES('J149','Junagadh','G6','Junagadh is a district of Gujarat');
INSERT INTO districts VALUES('K150','Kheda','G6','Kheda is a district of Gujarat');
INSERT INTO districts VALUES('K151','Kutch','G6','Kutch is a district of Gujarat');
INSERT INTO districts VALUES('M152','Mahisagar','G6','Mahisagar is a district of Gujarat');
INSERT INTO districts VALUES('M153','Mehsana','G6','Mehsana is a district of Gujarat');
INSERT INTO districts VALUES('M154','Morbi','G6','Morbi is a district of Gujarat');
INSERT INTO districts VALUES('N155','Narmada','G6','Narmada is a district of Gujarat');
INSERT INTO districts VALUES('N156','Navsari','G6','Navsari is a district of Gujarat');
INSERT INTO districts VALUES('P157','Panchmahal','G6','Panchmahal is a district of Gujarat');
INSERT INTO districts VALUES('P158','Patan','G6','Patan is a district of Gujarat');
INSERT INTO districts VALUES('P159','Porbandar','G6','Porbandar is a district of Gujarat');
INSERT INTO districts VALUES('R160','Rajkot','G6','Rajkot is a district of Gujarat');
INSERT INTO districts VALUES('S161','Sabarkantha','G6','Sabarkantha is a district of Gujarat');
INSERT INTO districts VALUES('S162','Surat','G6','Surat is a district of Gujarat');
INSERT INTO districts VALUES('S163','Surendranagar','G6','Surendranagar is a district of Gujarat');
INSERT INTO districts VALUES('T164','Tapi','G6','Tapi is a district of Gujarat');
INSERT INTO districts VALUES('V165','Vadodara','G6','Vadodara is a district of Gujarat');
INSERT INTO districts VALUES('V166','Valsad','G6','Valsad is a district of Gujarat');
INSERT INTO districts VALUES('A167','Ambala','H7','Ambala is a district of Haryana');
INSERT INTO districts VALUES('B168','Bhiwani','H7','Bhiwani is a district of Haryana');
INSERT INTO districts VALUES('CD169','Charkhi Dadri','H7','Charkhi Dadri is a district of Haryana');
INSERT INTO districts VALUES('F170','Faridabad','H7','Faridabad is a district of Haryana');
INSERT INTO districts VALUES('F171','Fatehabad','H7','Fatehabad is a district of Haryana');
INSERT INTO districts VALUES('G172','Gurugram','H7','Gurugram is a district of Haryana');
INSERT INTO districts VALUES('H173','Hisar','H7','Hisar is a district of Haryana');
INSERT INTO districts VALUES('J174','Jhajjar','H7','Jhajjar is a district of Haryana');
INSERT INTO districts VALUES('J175','Jind','H7','Jind is a district of Haryana');
INSERT INTO districts VALUES('K176','Kaithal','H7','Kaithal is a district of Haryana');
INSERT INTO districts VALUES('K177','Karnal','H7','Karnal is a district of Haryana');
INSERT INTO districts VALUES('K178','Kurukshetra','H7','Kurukshetra is a district of Haryana');
INSERT INTO districts VALUES('M179','Mahendragarh','H7','Mahendragarh is a district of Haryana');
INSERT INTO districts VALUES('M180','Mewat','H7','Mewat is a district of Haryana');
INSERT INTO districts VALUES('P181','Palwal','H7','Palwal is a district of Haryana');
INSERT INTO districts VALUES('P182','Panchkula','H7','Panchkula is a district of Haryana');
INSERT INTO districts VALUES('P183','Panipat','H7','Panipat is a district of Haryana');
INSERT INTO districts VALUES('R184','Rewari','H7','Rewari is a district of Haryana');
INSERT INTO districts VALUES('R185','Rohtak','H7','Rohtak is a district of Haryana');
INSERT INTO districts VALUES('S186','Sirsa','H7','Sirsa is a district of Haryana');
INSERT INTO districts VALUES('S187','Sonipat','H7','Sonipat is a district of Haryana');
INSERT INTO districts VALUES('Y188','Yamunanagar','H7','Yamunanagar is a district of Haryana');
INSERT INTO districts VALUES('B189','Bilaspur','HP8','Bilaspur is a district of Himachal Pradesh');
INSERT INTO districts VALUES('C190','Chamba','HP8','Chamba is a district of Himachal Pradesh');
INSERT INTO districts VALUES('H191','Hamirpur','HP8','Hamirpur is a district of Himachal Pradesh');
INSERT INTO districts VALUES('K192','Kangra','HP8','Kangra is a district of Himachal Pradesh');
INSERT INTO districts VALUES('K193','Kinnaur','HP8','Kinnaur is a district of Himachal Pradesh');
INSERT INTO districts VALUES('K194','Kullu','HP8','Kullu is a district of Himachal Pradesh');
INSERT INTO districts VALUES('LS195','Lahaul Spiti','HP8','Lahaul Spiti is a district of Himachal Pradesh');
INSERT INTO districts VALUES('M196','Mandi','HP8','Mandi is a district of Himachal Pradesh');
INSERT INTO districts VALUES('S197','Shimla','HP8','Shimla is a district of Himachal Pradesh');
INSERT INTO districts VALUES('S198','Sirmaur','HP8','Sirmaur is a district of Himachal Pradesh');
INSERT INTO districts VALUES('S199','Solan','HP8','Solan is a district of Himachal Pradesh');
INSERT INTO districts VALUES('U200','Una','HP8','Una is a district of Himachal Pradesh');
INSERT INTO districts VALUES('A201','Anantnag','JK9','Anantnag is a district of Jammu Kashmir');
INSERT INTO districts VALUES('B202','Bandipora','JK9','Bandipora is a district of Jammu Kashmir');
INSERT INTO districts VALUES('B203','Baramulla','JK9','Baramulla is a district of Jammu Kashmir');
INSERT INTO districts VALUES('B204','Budgam','JK9','Budgam is a district of Jammu Kashmir');
INSERT INTO districts VALUES('D205','Doda','JK9','Doda is a district of Jammu Kashmir');
INSERT INTO districts VALUES('G206','Ganderbal','JK9','Ganderbal is a district of Jammu Kashmir');
INSERT INTO districts VALUES('J207','Jammu','JK9','Jammu is a district of Jammu Kashmir');
INSERT INTO districts VALUES('K208','Kargil','JK9','Kargil is a district of Jammu Kashmir');
INSERT INTO districts VALUES('K209','Kathua','JK9','Kathua is a district of Jammu Kashmir');
INSERT INTO districts VALUES('K210','Kishtwar','JK9','Kishtwar is a district of Jammu Kashmir');
INSERT INTO districts VALUES('K211','Kulgam','JK9','Kulgam is a district of Jammu Kashmir');
INSERT INTO districts VALUES('K212','Kupwara','JK9','Kupwara is a district of Jammu Kashmir');
INSERT INTO districts VALUES('L213','Leh','JK9','Leh is a district of Jammu Kashmir');
INSERT INTO districts VALUES('P214','Poonch','JK9','Poonch is a district of Jammu Kashmir');
INSERT INTO districts VALUES('P215','Pulwama','JK9','Pulwama is a district of Jammu Kashmir');
INSERT INTO districts VALUES('R216','Rajouri','JK9','Rajouri is a district of Jammu Kashmir');
INSERT INTO districts VALUES('R217','Ramban','JK9','Ramban is a district of Jammu Kashmir');
INSERT INTO districts VALUES('R218','Reasi','JK9','Reasi is a district of Jammu Kashmir');
INSERT INTO districts VALUES('S219','Samba','JK9','Samba is a district of Jammu Kashmir');
INSERT INTO districts VALUES('S220','Shopian','JK9','Shopian is a district of Jammu Kashmir');
INSERT INTO districts VALUES('S221','Srinagar','JK9','Srinagar is a district of Jammu Kashmir');
INSERT INTO districts VALUES('U222','Udhampur','JK9','Udhampur is a district of Jammu Kashmir');
INSERT INTO districts VALUES('B223','Bokaro','J10','Bokaro is a district of Jharkhand');
INSERT INTO districts VALUES('C224','Chatra','J10','Chatra is a district of Jharkhand');
INSERT INTO districts VALUES('D225','Deoghar','J10','Deoghar is a district of Jharkhand');
INSERT INTO districts VALUES('D226','Dhanbad','J10','Dhanbad is a district of Jharkhand');
INSERT INTO districts VALUES('D227','Dumka','J10','Dumka is a district of Jharkhand');
INSERT INTO districts VALUES('ES228','East Singhbhum','J10','East Singhbhum is a district of Jharkhand');
INSERT INTO districts VALUES('G229','Garhwa','J10','Garhwa is a district of Jharkhand');
INSERT INTO districts VALUES('G230','Giridih','J10','Giridih is a district of Jharkhand');
INSERT INTO districts VALUES('G231','Godda','J10','Godda is a district of Jharkhand');
INSERT INTO districts VALUES('G232','Gumla','J10','Gumla is a district of Jharkhand');
INSERT INTO districts VALUES('H233','Hazaribagh','J10','Hazaribagh is a district of Jharkhand');
INSERT INTO districts VALUES('J234','Jamtara','J10','Jamtara is a district of Jharkhand');
INSERT INTO districts VALUES('K235','Khunti','J10','Khunti is a district of Jharkhand');
INSERT INTO districts VALUES('K236','Koderma','J10','Koderma is a district of Jharkhand');
INSERT INTO districts VALUES('L237','Latehar','J10','Latehar is a district of Jharkhand');
INSERT INTO districts VALUES('L238','Lohardaga','J10','Lohardaga is a district of Jharkhand');
INSERT INTO districts VALUES('P239','Pakur','J10','Pakur is a district of Jharkhand');
INSERT INTO districts VALUES('P240','Palamu','J10','Palamu is a district of Jharkhand');
INSERT INTO districts VALUES('R241','Ramgarh','J10','Ramgarh is a district of Jharkhand');
INSERT INTO districts VALUES('R242','Ranchi','J10','Ranchi is a district of Jharkhand');
INSERT INTO districts VALUES('S243','Sahebganj','J10','Sahebganj is a district of Jharkhand');
INSERT INTO districts VALUES('SK244','Seraikela Kharsawan','J10','Seraikela Kharsawan is a district of Jharkhand');
INSERT INTO districts VALUES('S245','Simdega','J10','Simdega is a district of Jharkhand');
INSERT INTO districts VALUES('WS246','West Singhbhum','J10','West Singhbhum is a district of Jharkhand');
INSERT INTO districts VALUES('B247','Bagalkot','K11','Bagalkot is a district of Karnataka');
INSERT INTO districts VALUES('BR248','Bangalore Rural','K11','Bangalore Rural is a district of Karnataka');
INSERT INTO districts VALUES('BU249','Bangalore Urban','K11','Bangalore Urban is a district of Karnataka');
INSERT INTO districts VALUES('B250','Belgaum','K11','Belgaum is a district of Karnataka');
INSERT INTO districts VALUES('B251','Bellary','K11','Bellary is a district of Karnataka');
INSERT INTO districts VALUES('B252','Bidar','K11','Bidar is a district of Karnataka');
INSERT INTO districts VALUES('V253','Vijayapura','K11','Vijayapura is a district of Karnataka');
INSERT INTO districts VALUES('C254','Chamarajanagar','K11','Chamarajanagar is a district of Karnataka');
INSERT INTO districts VALUES('C255','Chikkaballapur','K11','Chikkaballapur is a district of Karnataka');
INSERT INTO districts VALUES('C256','Chikkamagaluru','K11','Chikkamagaluru is a district of Karnataka');
INSERT INTO districts VALUES('C257','Chitradurga','K11','Chitradurga is a district of Karnataka');
INSERT INTO districts VALUES('DK258','Dakshina Kannada','K11','Dakshina Kannada is a district of Karnataka');
INSERT INTO districts VALUES('D259','Davanagere','K11','Davanagere is a district of Karnataka');
INSERT INTO districts VALUES('D260','Dharwad','K11','Dharwad is a district of Karnataka');
INSERT INTO districts VALUES('G261','Gadag','K11','Gadag is a district of Karnataka');
INSERT INTO districts VALUES('G262','Gulbarga','K11','Gulbarga is a district of Karnataka');
INSERT INTO districts VALUES('H263','Hassan','K11','Hassan is a district of Karnataka');
INSERT INTO districts VALUES('H264','Haveri','K11','Haveri is a district of Karnataka');
INSERT INTO districts VALUES('K265','Kodagu','K11','Kodagu is a district of Karnataka');
INSERT INTO districts VALUES('K266','Kolar','K11','Kolar is a district of Karnataka');
INSERT INTO districts VALUES('K267','Koppal','K11','Koppal is a district of Karnataka');
INSERT INTO districts VALUES('M268','Mandya','K11','Mandya is a district of Karnataka');
INSERT INTO districts VALUES('M269','Mysore','K11','Mysore is a district of Karnataka');
INSERT INTO districts VALUES('R270','Raichur','K11','Raichur is a district of Karnataka');
INSERT INTO districts VALUES('R271','Ramanagara','K11','Ramanagara is a district of Karnataka');
INSERT INTO districts VALUES('S272','Shimoga','K11','Shimoga is a district of Karnataka');
INSERT INTO districts VALUES('T273','Tumkur','K11','Tumkur is a district of Karnataka');
INSERT INTO districts VALUES('U274','Udupi','K11','Udupi is a district of Karnataka');
INSERT INTO districts VALUES('UK275','Uttara Kannada','K11','Uttara Kannada is a district of Karnataka');
INSERT INTO districts VALUES('Y276','Yadgir','K11','Yadgir is a district of Karnataka');
INSERT INTO districts VALUES('A277','Alappuzha','K12','Alappuzha is a district of Kerala');
INSERT INTO districts VALUES('E278','Ernakulam','K12','Ernakulam is a district of Kerala');
INSERT INTO districts VALUES('I279','Idukki','K12','Idukki is a district of Kerala');
INSERT INTO districts VALUES('K280','Kannur','K12','Kannur is a district of Kerala');
INSERT INTO districts VALUES('K281','Kasaragod','K12','Kasaragod is a district of Kerala');
INSERT INTO districts VALUES('K282','Kollam','K12','Kollam is a district of Kerala');
INSERT INTO districts VALUES('K283','Kottayam','K12','Kottayam is a district of Kerala');
INSERT INTO districts VALUES('K284','Kozhikode','K12','Kozhikode is a district of Kerala');
INSERT INTO districts VALUES('M285','Malappuram','K12','Malappuram is a district of Kerala');
INSERT INTO districts VALUES('P286','Palakkad','K12','Palakkad is a district of Kerala');
INSERT INTO districts VALUES('P287','Pathanamthitta','K12','Pathanamthitta is a district of Kerala');
INSERT INTO districts VALUES('T288','Thiruvananthapuram','K12','Thiruvananthapuram is a district of Kerala');
INSERT INTO districts VALUES('T289','Thrissur','K12','Thrissur is a district of Kerala');
INSERT INTO districts VALUES('W290','Wayanad','K12','Wayanad is a district of Kerala');
INSERT INTO districts VALUES('AM291','Agar Malwa','MP13','Agar Malwa is a district of Madhya Pradesh');
INSERT INTO districts VALUES('A292','Alirajpur','MP13','Alirajpur is a district of Madhya Pradesh');
INSERT INTO districts VALUES('A293','Anuppur','MP13','Anuppur is a district of Madhya Pradesh');
INSERT INTO districts VALUES('A294','Ashoknagar','MP13','Ashoknagar is a district of Madhya Pradesh');
INSERT INTO districts VALUES('B295','Balaghat','MP13','Balaghat is a district of Madhya Pradesh');
INSERT INTO districts VALUES('B296','Barwani','MP13','Barwani is a district of Madhya Pradesh');
INSERT INTO districts VALUES('B297','Betul','MP13','Betul is a district of Madhya Pradesh');
INSERT INTO districts VALUES('B298','Bhind','MP13','Bhind is a district of Madhya Pradesh');
INSERT INTO districts VALUES('B299','Bhopal','MP13','Bhopal is a district of Madhya Pradesh');
INSERT INTO districts VALUES('B300','Burhanpur','MP13','Burhanpur is a district of Madhya Pradesh');
INSERT INTO districts VALUES('C301','Chhatarpur','MP13','Chhatarpur is a district of Madhya Pradesh');
INSERT INTO districts VALUES('C302','Chhindwara','MP13','Chhindwara is a district of Madhya Pradesh');
INSERT INTO districts VALUES('D303','Damoh','MP13','Damoh is a district of Madhya Pradesh');
INSERT INTO districts VALUES('D304','Datia','MP13','Datia is a district of Madhya Pradesh');
INSERT INTO districts VALUES('D305','Dewas','MP13','Dewas is a district of Madhya Pradesh');
INSERT INTO districts VALUES('D306','Dhar','MP13','Dhar is a district of Madhya Pradesh');
INSERT INTO districts VALUES('D307','Dindori','MP13','Dindori is a district of Madhya Pradesh');
INSERT INTO districts VALUES('G308','Guna','MP13','Guna is a district of Madhya Pradesh');
INSERT INTO districts VALUES('G309','Gwalior','MP13','Gwalior is a district of Madhya Pradesh');
INSERT INTO districts VALUES('H310','Harda','MP13','Harda is a district of Madhya Pradesh');
INSERT INTO districts VALUES('H311','Hoshangabad','MP13','Hoshangabad is a district of Madhya Pradesh');
INSERT INTO districts VALUES('I312','Indore','MP13','Indore is a district of Madhya Pradesh');
INSERT INTO districts VALUES('J313','Jabalpur','MP13','Jabalpur is a district of Madhya Pradesh');
INSERT INTO districts VALUES('J314','Jhabua','MP13','Jhabua is a district of Madhya Pradesh');
INSERT INTO districts VALUES('K315','Katni','MP13','Katni is a district of Madhya Pradesh');
INSERT INTO districts VALUES('K316','Khandwa','MP13','Khandwa is a district of Madhya Pradesh');
INSERT INTO districts VALUES('K317','Khargone','MP13','Khargone is a district of Madhya Pradesh');
INSERT INTO districts VALUES('M318','Mandla','MP13','Mandla is a district of Madhya Pradesh');
INSERT INTO districts VALUES('M319','Mandsaur','MP13','Mandsaur is a district of Madhya Pradesh');
INSERT INTO districts VALUES('M320','Morena','MP13','Morena is a district of Madhya Pradesh');
INSERT INTO districts VALUES('N321','Narsinghpur','MP13','Narsinghpur is a district of Madhya Pradesh');
INSERT INTO districts VALUES('N322','Neemuch','MP13','Neemuch is a district of Madhya Pradesh');
INSERT INTO districts VALUES('P323','Panna','MP13','Panna is a district of Madhya Pradesh');
INSERT INTO districts VALUES('R324','Raisen','MP13','Raisen is a district of Madhya Pradesh');
INSERT INTO districts VALUES('R325','Rajgarh','MP13','Rajgarh is a district of Madhya Pradesh');
INSERT INTO districts VALUES('R326','Ratlam','MP13','Ratlam is a district of Madhya Pradesh');
INSERT INTO districts VALUES('R327','Rewa','MP13','Rewa is a district of Madhya Pradesh');
INSERT INTO districts VALUES('S328','Sagar','MP13','Sagar is a district of Madhya Pradesh');
INSERT INTO districts VALUES('S329','Satna','MP13','Satna is a district of Madhya Pradesh');
INSERT INTO districts VALUES('S330','Sehore','MP13','Sehore is a district of Madhya Pradesh');
INSERT INTO districts VALUES('S331','Seoni','MP13','Seoni is a district of Madhya Pradesh');
INSERT INTO districts VALUES('S332','Shahdol','MP13','Shahdol is a district of Madhya Pradesh');
INSERT INTO districts VALUES('S333','Shajapur','MP13','Shajapur is a district of Madhya Pradesh');
INSERT INTO districts VALUES('S334','Sheopur','MP13','Sheopur is a district of Madhya Pradesh');
INSERT INTO districts VALUES('S335','Shivpuri','MP13','Shivpuri is a district of Madhya Pradesh');
INSERT INTO districts VALUES('S336','Sidhi','MP13','Sidhi is a district of Madhya Pradesh');
INSERT INTO districts VALUES('S337','Singrauli','MP13','Singrauli is a district of Madhya Pradesh');
INSERT INTO districts VALUES('T338','Tikamgarh','MP13','Tikamgarh is a district of Madhya Pradesh');
INSERT INTO districts VALUES('U339','Ujjain','MP13','Ujjain is a district of Madhya Pradesh');
INSERT INTO districts VALUES('U340','Umaria','MP13','Umaria is a district of Madhya Pradesh');
INSERT INTO districts VALUES('V341','Vidisha','MP13','Vidisha is a district of Madhya Pradesh');
INSERT INTO districts VALUES('A342','Ahmednagar','M14','Ahmednagar is a district of Maharashtra');
INSERT INTO districts VALUES('A343','Akola','M14','Akola is a district of Maharashtra');
INSERT INTO districts VALUES('A344','Amravati','M14','Amravati is a district of Maharashtra');
INSERT INTO districts VALUES('A345','Aurangabad','M14','Aurangabad is a district of Maharashtra');
INSERT INTO districts VALUES('B346','Beed','M14','Beed is a district of Maharashtra');
INSERT INTO districts VALUES('B347','Bhandara','M14','Bhandara is a district of Maharashtra');
INSERT INTO districts VALUES('B348','Buldhana','M14','Buldhana is a district of Maharashtra');
INSERT INTO districts VALUES('C349','Chandrapur','M14','Chandrapur is a district of Maharashtra');
INSERT INTO districts VALUES('D350','Dhule','M14','Dhule is a district of Maharashtra');
INSERT INTO districts VALUES('G351','Gadchiroli','M14','Gadchiroli is a district of Maharashtra');
INSERT INTO districts VALUES('G352','Gondia','M14','Gondia is a district of Maharashtra');
INSERT INTO districts VALUES('H353','Hingoli','M14','Hingoli is a district of Maharashtra');
INSERT INTO districts VALUES('J354','Jalgaon','M14','Jalgaon is a district of Maharashtra');
INSERT INTO districts VALUES('J355','Jalna','M14','Jalna is a district of Maharashtra');
INSERT INTO districts VALUES('K356','Kolhapur','M14','Kolhapur is a district of Maharashtra');
INSERT INTO districts VALUES('L357','Latur','M14','Latur is a district of Maharashtra');
INSERT INTO districts VALUES('MC358','Mumbai City','M14','Mumbai City is a district of Maharashtra');
INSERT INTO districts VALUES('MS359','Mumbai Suburban','M14','Mumbai Suburban is a district of Maharashtra');
INSERT INTO districts VALUES('N360','Nagpur','M14','Nagpur is a district of Maharashtra');
INSERT INTO districts VALUES('N361','Nanded','M14','Nanded is a district of Maharashtra');
INSERT INTO districts VALUES('N362','Nandurbar','M14','Nandurbar is a district of Maharashtra');
INSERT INTO districts VALUES('N363','Nashik','M14','Nashik is a district of Maharashtra');
INSERT INTO districts VALUES('O364','Osmanabad','M14','Osmanabad is a district of Maharashtra');
INSERT INTO districts VALUES('P365','Palghar','M14','Palghar is a district of Maharashtra');
INSERT INTO districts VALUES('P366','Parbhani','M14','Parbhani is a district of Maharashtra');
INSERT INTO districts VALUES('P367','Pune','M14','Pune is a district of Maharashtra');
INSERT INTO districts VALUES('R368','Raigad','M14','Raigad is a district of Maharashtra');
INSERT INTO districts VALUES('R369','Ratnagiri','M14','Ratnagiri is a district of Maharashtra');
INSERT INTO districts VALUES('S370','Sangli','M14','Sangli is a district of Maharashtra');
INSERT INTO districts VALUES('S371','Satara','M14','Satara is a district of Maharashtra');
INSERT INTO districts VALUES('S372','Sindhudurg','M14','Sindhudurg is a district of Maharashtra');
INSERT INTO districts VALUES('S373','Solapur','M14','Solapur is a district of Maharashtra');
INSERT INTO districts VALUES('T374','Thane','M14','Thane is a district of Maharashtra');
INSERT INTO districts VALUES('W375','Wardha','M14','Wardha is a district of Maharashtra');
INSERT INTO districts VALUES('W376','Washim','M14','Washim is a district of Maharashtra');
INSERT INTO districts VALUES('Y377','Yavatmal','M14','Yavatmal is a district of Maharashtra');
INSERT INTO districts VALUES('B378','Bishnupur','M15','Bishnupur is a district of Manipur');
INSERT INTO districts VALUES('C379','Chandel','M15','Chandel is a district of Manipur');
INSERT INTO districts VALUES('C380','Churachandpur','M15','Churachandpur is a district of Manipur');
INSERT INTO districts VALUES('IE381','Imphal East','M15','Imphal East is a district of Manipur');
INSERT INTO districts VALUES('IW382','Imphal West','M15','Imphal West is a district of Manipur');
INSERT INTO districts VALUES('J383','Jiribam','M15','Jiribam is a district of Manipur');
INSERT INTO districts VALUES('K384','Kakching','M15','Kakching is a district of Manipur');
INSERT INTO districts VALUES('K385','Kamjong','M15','Kamjong is a district of Manipur');
INSERT INTO districts VALUES('K386','Kangpokpi','M15','Kangpokpi is a district of Manipur');
INSERT INTO districts VALUES('N387','Noney','M15','Noney is a district of Manipur');
INSERT INTO districts VALUES('P388','Pherzawl','M15','Pherzawl is a district of Manipur');
INSERT INTO districts VALUES('S389','Senapati','M15','Senapati is a district of Manipur');
INSERT INTO districts VALUES('T390','Tamenglong','M15','Tamenglong is a district of Manipur');
INSERT INTO districts VALUES('T391','Tengnoupal','M15','Tengnoupal is a district of Manipur');
INSERT INTO districts VALUES('T392','Thoubal','M15','Thoubal is a district of Manipur');
INSERT INTO districts VALUES('U393','Ukhrul','M15','Ukhrul is a district of Manipur');
INSERT INTO districts VALUES('EGH394','East Garo Hills','M16','East Garo Hills is a district of Meghalaya');
INSERT INTO districts VALUES('EJH395','East Jaintia Hills','M16','East Jaintia Hills is a district of Meghalaya');
INSERT INTO districts VALUES('EKH396','East Khasi Hills','M16','East Khasi Hills is a district of Meghalaya');
INSERT INTO districts VALUES('NGH397','North Garo Hills','M16','North Garo Hills is a district of Meghalaya');
INSERT INTO districts VALUES('RB398','Ri Bhoi','M16','Ri Bhoi is a district of Meghalaya');
INSERT INTO districts VALUES('SGH399','South Garo Hills','M16','South Garo Hills is a district of Meghalaya');
INSERT INTO districts VALUES('SWGH400','South West Garo Hills','M16','South West Garo Hills is a district of Meghalaya');
INSERT INTO districts VALUES('SWKH401','South West Khasi Hills','M16','South West Khasi Hills is a district of Meghalaya');
INSERT INTO districts VALUES('WGH402','West Garo Hills','M16','West Garo Hills is a district of Meghalaya');
INSERT INTO districts VALUES('WJH403','West Jaintia Hills','M16','West Jaintia Hills is a district of Meghalaya');
INSERT INTO districts VALUES('WKH404','West Khasi Hills','M16','West Khasi Hills is a district of Meghalaya');
INSERT INTO districts VALUES('A405','Aizawl','M17','Aizawl is a district of Mizoram');
INSERT INTO districts VALUES('C406','Champhai','M17','Champhai is a district of Mizoram');
INSERT INTO districts VALUES('K407','Kolasib','M17','Kolasib is a district of Mizoram');
INSERT INTO districts VALUES('L408','Lawngtlai','M17','Lawngtlai is a district of Mizoram');
INSERT INTO districts VALUES('L409','Lunglei','M17','Lunglei is a district of Mizoram');
INSERT INTO districts VALUES('M410','Mamit','M17','Mamit is a district of Mizoram');
INSERT INTO districts VALUES('S411','Saiha','M17','Saiha is a district of Mizoram');
INSERT INTO districts VALUES('S412','Serchhip','M17','Serchhip is a district of Mizoram');
INSERT INTO districts VALUES('A413','Aizawl','M17','Aizawl is a district of Mizoram');
INSERT INTO districts VALUES('C414','Champhai','M17','Champhai is a district of Mizoram');
INSERT INTO districts VALUES('K415','Kolasib','M17','Kolasib is a district of Mizoram');
INSERT INTO districts VALUES('L416','Lawngtlai','M17','Lawngtlai is a district of Mizoram');
INSERT INTO districts VALUES('L417','Lunglei','M17','Lunglei is a district of Mizoram');
INSERT INTO districts VALUES('M418','Mamit','M17','Mamit is a district of Mizoram');
INSERT INTO districts VALUES('S419','Saiha','M17','Saiha is a district of Mizoram');
INSERT INTO districts VALUES('S420','Serchhip','M17','Serchhip is a district of Mizoram');
INSERT INTO districts VALUES('D421','Dimapur','N18','Dimapur is a district of Nagaland');
INSERT INTO districts VALUES('K422','Kiphire','N18','Kiphire is a district of Nagaland');
INSERT INTO districts VALUES('K423','Kohima','N18','Kohima is a district of Nagaland');
INSERT INTO districts VALUES('L424','Longleng','N18','Longleng is a district of Nagaland');
INSERT INTO districts VALUES('M425','Mokokchung','N18','Mokokchung is a district of Nagaland');
INSERT INTO districts VALUES('M426','Mon','N18','Mon is a district of Nagaland');
INSERT INTO districts VALUES('P427','Peren','N18','Peren is a district of Nagaland');
INSERT INTO districts VALUES('P428','Phek','N18','Phek is a district of Nagaland');
INSERT INTO districts VALUES('T429','Tuensang','N18','Tuensang is a district of Nagaland');
INSERT INTO districts VALUES('W430','Wokha','N18','Wokha is a district of Nagaland');
INSERT INTO districts VALUES('Z431','Zunheboto','N18','Zunheboto is a district of Nagaland');
INSERT INTO districts VALUES('A432','Angul','O19','Angul is a district of Odisha');
INSERT INTO districts VALUES('B433','Balangir','O19','Balangir is a district of Odisha');
INSERT INTO districts VALUES('B434','Balasore','O19','Balasore is a district of Odisha');
INSERT INTO districts VALUES('B435','Bargarh','O19','Bargarh is a district of Odisha');
INSERT INTO districts VALUES('B436','Bhadrak','O19','Bhadrak is a district of Odisha');
INSERT INTO districts VALUES('B437','Boudh','O19','Boudh is a district of Odisha');
INSERT INTO districts VALUES('C438','Cuttack','O19','Cuttack is a district of Odisha');
INSERT INTO districts VALUES('D439','Debagarh','O19','Debagarh is a district of Odisha');
INSERT INTO districts VALUES('D440','Dhenkanal','O19','Dhenkanal is a district of Odisha');
INSERT INTO districts VALUES('G441','Gajapati','O19','Gajapati is a district of Odisha');
INSERT INTO districts VALUES('G442','Ganjam','O19','Ganjam is a district of Odisha');
INSERT INTO districts VALUES('J443','Jagatsinghpur','O19','Jagatsinghpur is a district of Odisha');
INSERT INTO districts VALUES('J444','Jajpur','O19','Jajpur is a district of Odisha');
INSERT INTO districts VALUES('J445','Jharsuguda','O19','Jharsuguda is a district of Odisha');
INSERT INTO districts VALUES('K446','Kalahandi','O19','Kalahandi is a district of Odisha');
INSERT INTO districts VALUES('K447','Kandhamal','O19','Kandhamal is a district of Odisha');
INSERT INTO districts VALUES('K448','Kendrapara','O19','Kendrapara is a district of Odisha');
INSERT INTO districts VALUES('K449','Kendujhar','O19','Kendujhar is a district of Odisha');
INSERT INTO districts VALUES('K450','Khordha','O19','Khordha is a district of Odisha');
INSERT INTO districts VALUES('K451','Koraput','O19','Koraput is a district of Odisha');
INSERT INTO districts VALUES('M452','Malkangiri','O19','Malkangiri is a district of Odisha');
INSERT INTO districts VALUES('M453','Mayurbhanj','O19','Mayurbhanj is a district of Odisha');
INSERT INTO districts VALUES('N454','Nabarangpur','O19','Nabarangpur is a district of Odisha');
INSERT INTO districts VALUES('N455','Nayagarh','O19','Nayagarh is a district of Odisha');
INSERT INTO districts VALUES('N456','Nuapada','O19','Nuapada is a district of Odisha');
INSERT INTO districts VALUES('P457','Puri','O19','Puri is a district of Odisha');
INSERT INTO districts VALUES('R458','Rayagada','O19','Rayagada is a district of Odisha');
INSERT INTO districts VALUES('S459','Sambalpur','O19','Sambalpur is a district of Odisha');
INSERT INTO districts VALUES('S460','Subarnapur','O19','Subarnapur is a district of Odisha');
INSERT INTO districts VALUES('S461','Sundergarh','O19','Sundergarh is a district of Odisha');
INSERT INTO districts VALUES('A462','Amritsar','P20','Amritsar is a district of Punjab');
INSERT INTO districts VALUES('B463','Barnala','P20','Barnala is a district of Punjab');
INSERT INTO districts VALUES('B464','Bathinda','P20','Bathinda is a district of Punjab');
INSERT INTO districts VALUES('F465','Faridkot','P20','Faridkot is a district of Punjab');
INSERT INTO districts VALUES('FS466','Fatehgarh Sahib','P20','Fatehgarh Sahib is a district of Punjab');
INSERT INTO districts VALUES('F467','Fazilka','P20','Fazilka is a district of Punjab');
INSERT INTO districts VALUES('F468','Firozpur','P20','Firozpur is a district of Punjab');
INSERT INTO districts VALUES('G469','Gurdaspur','P20','Gurdaspur is a district of Punjab');
INSERT INTO districts VALUES('H470','Hoshiarpur','P20','Hoshiarpur is a district of Punjab');
INSERT INTO districts VALUES('J471','Jalandhar','P20','Jalandhar is a district of Punjab');
INSERT INTO districts VALUES('K472','Kapurthala','P20','Kapurthala is a district of Punjab');
INSERT INTO districts VALUES('L473','Ludhiana','P20','Ludhiana is a district of Punjab');
INSERT INTO districts VALUES('M474','Mansa','P20','Mansa is a district of Punjab');
INSERT INTO districts VALUES('M475','Moga','P20','Moga is a district of Punjab');
INSERT INTO districts VALUES('M476','Mohali','P20','Mohali is a district of Punjab');
INSERT INTO districts VALUES('M477','Muktsar','P20','Muktsar is a district of Punjab');
INSERT INTO districts VALUES('P478','Pathankot','P20','Pathankot is a district of Punjab');
INSERT INTO districts VALUES('P479','Patiala','P20','Patiala is a district of Punjab');
INSERT INTO districts VALUES('R480','Rupnagar','P20','Rupnagar is a district of Punjab');
INSERT INTO districts VALUES('S481','Sangrur','P20','Sangrur is a district of Punjab');
INSERT INTO districts VALUES('SBSN482','Shaheed Bhagat Singh Nagar','P20','Shaheed Bhagat Singh Nagar is a district of Punjab');
INSERT INTO districts VALUES('TT483','Tarn Taran','P20','Tarn Taran is a district of Punjab');
INSERT INTO districts VALUES('A484','Ajmer','R21','Ajmer is a district of Rajasthan');
INSERT INTO districts VALUES('A485','Alwar','R21','Alwar is a district of Rajasthan');
INSERT INTO districts VALUES('B486','Banswara','R21','Banswara is a district of Rajasthan');
INSERT INTO districts VALUES('B487','Baran','R21','Baran is a district of Rajasthan');
INSERT INTO districts VALUES('B488','Barmer','R21','Barmer is a district of Rajasthan');
INSERT INTO districts VALUES('B489','Bharatpur','R21','Bharatpur is a district of Rajasthan');
INSERT INTO districts VALUES('B490','Bhilwara','R21','Bhilwara is a district of Rajasthan');
INSERT INTO districts VALUES('B491','Bikaner','R21','Bikaner is a district of Rajasthan');
INSERT INTO districts VALUES('B492','Bundi','R21','Bundi is a district of Rajasthan');
INSERT INTO districts VALUES('C493','Chittorgarh','R21','Chittorgarh is a district of Rajasthan');
INSERT INTO districts VALUES('C494','Churu','R21','Churu is a district of Rajasthan');
INSERT INTO districts VALUES('D495','Dausa','R21','Dausa is a district of Rajasthan');
INSERT INTO districts VALUES('D496','Dholpur','R21','Dholpur is a district of Rajasthan');
INSERT INTO districts VALUES('D497','Dungarpur','R21','Dungarpur is a district of Rajasthan');
INSERT INTO districts VALUES('G498','Ganganagar','R21','Ganganagar is a district of Rajasthan');
INSERT INTO districts VALUES('H499','Hanumangarh','R21','Hanumangarh is a district of Rajasthan');
INSERT INTO districts VALUES('J500','Jaipur','R21','Jaipur is a district of Rajasthan');
INSERT INTO districts VALUES('J501','Jaisalmer','R21','Jaisalmer is a district of Rajasthan');
INSERT INTO districts VALUES('J502','Jalore','R21','Jalore is a district of Rajasthan');
INSERT INTO districts VALUES('J503','Jhalawar','R21','Jhalawar is a district of Rajasthan');
INSERT INTO districts VALUES('J504','Jhunjhunu','R21','Jhunjhunu is a district of Rajasthan');
INSERT INTO districts VALUES('J505','Jodhpur','R21','Jodhpur is a district of Rajasthan');
INSERT INTO districts VALUES('K506','Karauli','R21','Karauli is a district of Rajasthan');
INSERT INTO districts VALUES('K507','Kota','R21','Kota is a district of Rajasthan');
INSERT INTO districts VALUES('N508','Nagaur','R21','Nagaur is a district of Rajasthan');
INSERT INTO districts VALUES('P509','Pali','R21','Pali is a district of Rajasthan');
INSERT INTO districts VALUES('P510','Pratapgarh','R21','Pratapgarh is a district of Rajasthan');
INSERT INTO districts VALUES('R511','Rajsamand','R21','Rajsamand is a district of Rajasthan');
INSERT INTO districts VALUES('SM512','Sawai Madhopur','R21','Sawai Madhopur is a district of Rajasthan');
INSERT INTO districts VALUES('S513','Sikar','R21','Sikar is a district of Rajasthan');
INSERT INTO districts VALUES('S514','Sirohi','R21','Sirohi is a district of Rajasthan');
INSERT INTO districts VALUES('T515','Tonk','R21','Tonk is a district of Rajasthan');
INSERT INTO districts VALUES('U516','Udaipur','R21','Udaipur is a district of Rajasthan');
INSERT INTO districts VALUES('ES517','East Sikkim','S22','East Sikkim is a district of Sikkim');
INSERT INTO districts VALUES('NS518','North Sikkim','S22','North Sikkim is a district of Sikkim');
INSERT INTO districts VALUES('SS519','South Sikkim','S22','South Sikkim is a district of Sikkim');
INSERT INTO districts VALUES('WS520','West Sikkim','S22','West Sikkim is a district of Sikkim');
INSERT INTO districts VALUES('A521','Ariyalur','TN23','Ariyalur is a district of Tamil Nadu');
INSERT INTO districts VALUES('C522','Chennai','TN23','Chennai is a district of Tamil Nadu');
INSERT INTO districts VALUES('C523','Coimbatore','TN23','Coimbatore is a district of Tamil Nadu');
INSERT INTO districts VALUES('C524','Cuddalore','TN23','Cuddalore is a district of Tamil Nadu');
INSERT INTO districts VALUES('D525','Dharmapuri','TN23','Dharmapuri is a district of Tamil Nadu');
INSERT INTO districts VALUES('D526','Dindigul','TN23','Dindigul is a district of Tamil Nadu');
INSERT INTO districts VALUES('E527','Erode','TN23','Erode is a district of Tamil Nadu');
INSERT INTO districts VALUES('K528','Kanchipuram','TN23','Kanchipuram is a district of Tamil Nadu');
INSERT INTO districts VALUES('K529','Kanyakumari','TN23','Kanyakumari is a district of Tamil Nadu');
INSERT INTO districts VALUES('K530','Karur','TN23','Karur is a district of Tamil Nadu');
INSERT INTO districts VALUES('K531','Krishnagiri','TN23','Krishnagiri is a district of Tamil Nadu');
INSERT INTO districts VALUES('M532','Madurai','TN23','Madurai is a district of Tamil Nadu');
INSERT INTO districts VALUES('N533','Nagapattinam','TN23','Nagapattinam is a district of Tamil Nadu');
INSERT INTO districts VALUES('N534','Namakkal','TN23','Namakkal is a district of Tamil Nadu');
INSERT INTO districts VALUES('N535','Nilgiris','TN23','Nilgiris is a district of Tamil Nadu');
INSERT INTO districts VALUES('P536','Perambalur','TN23','Perambalur is a district of Tamil Nadu');
INSERT INTO districts VALUES('P537','Pudukkottai','TN23','Pudukkottai is a district of Tamil Nadu');
INSERT INTO districts VALUES('R538','Ramanathapuram','TN23','Ramanathapuram is a district of Tamil Nadu');
INSERT INTO districts VALUES('S539','Salem','TN23','Salem is a district of Tamil Nadu');
INSERT INTO districts VALUES('S540','Sivaganga','TN23','Sivaganga is a district of Tamil Nadu');
INSERT INTO districts VALUES('T541','Thanjavur','TN23','Thanjavur is a district of Tamil Nadu');
INSERT INTO districts VALUES('T542','Theni','TN23','Theni is a district of Tamil Nadu');
INSERT INTO districts VALUES('T543','Thoothukudi','TN23','Thoothukudi is a district of Tamil Nadu');
INSERT INTO districts VALUES('T544','Tiruchirappalli','TN23','Tiruchirappalli is a district of Tamil Nadu');
INSERT INTO districts VALUES('T545','Tirunelveli','TN23','Tirunelveli is a district of Tamil Nadu');
INSERT INTO districts VALUES('T546','Tiruppur','TN23','Tiruppur is a district of Tamil Nadu');
INSERT INTO districts VALUES('T547','Tiruvallur','TN23','Tiruvallur is a district of Tamil Nadu');
INSERT INTO districts VALUES('T548','Tiruvannamalai','TN23','Tiruvannamalai is a district of Tamil Nadu');
INSERT INTO districts VALUES('T549','Tiruvarur','TN23','Tiruvarur is a district of Tamil Nadu');
INSERT INTO districts VALUES('V550','Vellore','TN23','Vellore is a district of Tamil Nadu');
INSERT INTO districts VALUES('V551','Viluppuram','TN23','Viluppuram is a district of Tamil Nadu');
INSERT INTO districts VALUES('V552','Virudhunagar','TN23','Virudhunagar is a district of Tamil Nadu');
INSERT INTO districts VALUES('A553','Adilabad','T24','Adilabad is a district of Telangana');
INSERT INTO districts VALUES('BK554','Bhadradri Kothagudem','T24','Bhadradri Kothagudem is a district of Telangana');
INSERT INTO districts VALUES('H555','Hyderabad','T24','Hyderabad is a district of Telangana');
INSERT INTO districts VALUES('J556','Jagtial','T24','Jagtial is a district of Telangana');
INSERT INTO districts VALUES('J557','Jangaon','T24','Jangaon is a district of Telangana');
INSERT INTO districts VALUES('J558','Jayashankar','T24','Jayashankar is a district of Telangana');
INSERT INTO districts VALUES('J559','Jogulamba','T24','Jogulamba is a district of Telangana');
INSERT INTO districts VALUES('K560','Kamareddy','T24','Kamareddy is a district of Telangana');
INSERT INTO districts VALUES('K561','Karimnagar','T24','Karimnagar is a district of Telangana');
INSERT INTO districts VALUES('K562','Khammam','T24','Khammam is a district of Telangana');
INSERT INTO districts VALUES('KB563','Komaram Bheem','T24','Komaram Bheem is a district of Telangana');
INSERT INTO districts VALUES('M564','Mahabubabad','T24','Mahabubabad is a district of Telangana');
INSERT INTO districts VALUES('M565','Mahbubnagar','T24','Mahbubnagar is a district of Telangana');
INSERT INTO districts VALUES('M566','Mancherial','T24','Mancherial is a district of Telangana');
INSERT INTO districts VALUES('M567','Medak','T24','Medak is a district of Telangana');
INSERT INTO districts VALUES('M568','Medchal','T24','Medchal is a district of Telangana');
INSERT INTO districts VALUES('N569','Nagarkurnool','T24','Nagarkurnool is a district of Telangana');
INSERT INTO districts VALUES('N570','Nalgonda','T24','Nalgonda is a district of Telangana');
INSERT INTO districts VALUES('N571','Nirmal','T24','Nirmal is a district of Telangana');
INSERT INTO districts VALUES('N572','Nizamabad','T24','Nizamabad is a district of Telangana');
INSERT INTO districts VALUES('P573','Peddapalli','T24','Peddapalli is a district of Telangana');
INSERT INTO districts VALUES('RS574','Rajanna Sircilla','T24','Rajanna Sircilla is a district of Telangana');
INSERT INTO districts VALUES('RR575','Ranga Reddy','T24','Ranga Reddy is a district of Telangana');
INSERT INTO districts VALUES('S576','Sangareddy','T24','Sangareddy is a district of Telangana');
INSERT INTO districts VALUES('S577','Siddipet','T24','Siddipet is a district of Telangana');
INSERT INTO districts VALUES('S578','Suryapet','T24','Suryapet is a district of Telangana');
INSERT INTO districts VALUES('V579','Vikarabad','T24','Vikarabad is a district of Telangana');
INSERT INTO districts VALUES('W580','Wanaparthy','T24','Wanaparthy is a district of Telangana');
INSERT INTO districts VALUES('WR581','Warangal Rural','T24','Warangal Rural is a district of Telangana');
INSERT INTO districts VALUES('WU582','Warangal Urban','T24','Warangal Urban is a district of Telangana');
INSERT INTO districts VALUES('YB583','Yadadri Bhuvanagiri','T24','Yadadri Bhuvanagiri is a district of Telangana');
INSERT INTO districts VALUES('D584','Dhalai','T25','Dhalai is a district of Tripura');
INSERT INTO districts VALUES('G585','Gomati','T25','Gomati is a district of Tripura');
INSERT INTO districts VALUES('K586','Khowai','T25','Khowai is a district of Tripura');
INSERT INTO districts VALUES('NT587','North Tripura','T25','North Tripura is a district of Tripura');
INSERT INTO districts VALUES('S588','Sepahijala','T25','Sepahijala is a district of Tripura');
INSERT INTO districts VALUES('ST589','South Tripura','T25','South Tripura is a district of Tripura');
INSERT INTO districts VALUES('U590','Unakoti','T25','Unakoti is a district of Tripura');
INSERT INTO districts VALUES('WT591','West Tripura','T25','West Tripura is a district of Tripura');
INSERT INTO districts VALUES('A592','Agra','UP26','Agra is a district of Uttar Pradesh');
INSERT INTO districts VALUES('A593','Aligarh','UP26','Aligarh is a district of Uttar Pradesh');
INSERT INTO districts VALUES('A594','Allahabad','UP26','Allahabad is a district of Uttar Pradesh');
INSERT INTO districts VALUES('AN595','Ambedkar Nagar','UP26','Ambedkar Nagar is a district of Uttar Pradesh');
INSERT INTO districts VALUES('A596','Amethi','UP26','Amethi is a district of Uttar Pradesh');
INSERT INTO districts VALUES('A597','Amroha','UP26','Amroha is a district of Uttar Pradesh');
INSERT INTO districts VALUES('A598','Auraiya','UP26','Auraiya is a district of Uttar Pradesh');
INSERT INTO districts VALUES('A599','Azamgarh','UP26','Azamgarh is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B600','Baghpat','UP26','Baghpat is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B601','Bahraich','UP26','Bahraich is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B602','Ballia','UP26','Ballia is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B603','Balrampur','UP26','Balrampur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B604','Banda','UP26','Banda is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B605','Barabanki','UP26','Barabanki is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B606','Bareilly','UP26','Bareilly is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B607','Basti','UP26','Basti is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B608','Bhadohi','UP26','Bhadohi is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B609','Bijnor','UP26','Bijnor is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B610','Budaun','UP26','Budaun is a district of Uttar Pradesh');
INSERT INTO districts VALUES('B611','Bulandshahr','UP26','Bulandshahr is a district of Uttar Pradesh');
INSERT INTO districts VALUES('C612','Chandauli','UP26','Chandauli is a district of Uttar Pradesh');
INSERT INTO districts VALUES('C613','Chitrakoot','UP26','Chitrakoot is a district of Uttar Pradesh');
INSERT INTO districts VALUES('D614','Deoria','UP26','Deoria is a district of Uttar Pradesh');
INSERT INTO districts VALUES('E615','Etah','UP26','Etah is a district of Uttar Pradesh');
INSERT INTO districts VALUES('E616','Etawah','UP26','Etawah is a district of Uttar Pradesh');
INSERT INTO districts VALUES('F617','Faizabad','UP26','Faizabad is a district of Uttar Pradesh');
INSERT INTO districts VALUES('F618','Farrukhabad','UP26','Farrukhabad is a district of Uttar Pradesh');
INSERT INTO districts VALUES('F619','Fatehpur','UP26','Fatehpur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('F620','Firozabad','UP26','Firozabad is a district of Uttar Pradesh');
INSERT INTO districts VALUES('GBN621','Gautam Buddha Nagar','UP26','Gautam Buddha Nagar is a district of Uttar Pradesh');
INSERT INTO districts VALUES('G622','Ghaziabad','UP26','Ghaziabad is a district of Uttar Pradesh');
INSERT INTO districts VALUES('G623','Ghazipur','UP26','Ghazipur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('G624','Gonda','UP26','Gonda is a district of Uttar Pradesh');
INSERT INTO districts VALUES('G625','Gorakhpur','UP26','Gorakhpur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('H626','Hamirpur','UP26','Hamirpur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('H627','Hapur','UP26','Hapur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('H628','Hardoi','UP26','Hardoi is a district of Uttar Pradesh');
INSERT INTO districts VALUES('H629','Hathras','UP26','Hathras is a district of Uttar Pradesh');
INSERT INTO districts VALUES('J630','Jalaun','UP26','Jalaun is a district of Uttar Pradesh');
INSERT INTO districts VALUES('J631','Jaunpur','UP26','Jaunpur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('J632','Jhansi','UP26','Jhansi is a district of Uttar Pradesh');
INSERT INTO districts VALUES('K633','Kannauj','UP26','Kannauj is a district of Uttar Pradesh');
INSERT INTO districts VALUES('KD634','Kanpur Dehat','UP26','Kanpur Dehat is a district of Uttar Pradesh');
INSERT INTO districts VALUES('KN635','Kanpur Nagar','UP26','Kanpur Nagar is a district of Uttar Pradesh');
INSERT INTO districts VALUES('K636','Kasganj','UP26','Kasganj is a district of Uttar Pradesh');
INSERT INTO districts VALUES('K637','Kaushambi','UP26','Kaushambi is a district of Uttar Pradesh');
INSERT INTO districts VALUES('K638','Kheri','UP26','Kheri is a district of Uttar Pradesh');
INSERT INTO districts VALUES('K639','Kushinagar','UP26','Kushinagar is a district of Uttar Pradesh');
INSERT INTO districts VALUES('L640','Lalitpur','UP26','Lalitpur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('L641','Lucknow','UP26','Lucknow is a district of Uttar Pradesh');
INSERT INTO districts VALUES('M642','Maharajganj','UP26','Maharajganj is a district of Uttar Pradesh');
INSERT INTO districts VALUES('M643','Mahoba','UP26','Mahoba is a district of Uttar Pradesh');
INSERT INTO districts VALUES('M644','Mainpuri','UP26','Mainpuri is a district of Uttar Pradesh');
INSERT INTO districts VALUES('M645','Mathura','UP26','Mathura is a district of Uttar Pradesh');
INSERT INTO districts VALUES('M646','Mau','UP26','Mau is a district of Uttar Pradesh');
INSERT INTO districts VALUES('M647','Meerut','UP26','Meerut is a district of Uttar Pradesh');
INSERT INTO districts VALUES('M648','Mirzapur','UP26','Mirzapur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('M649','Moradabad','UP26','Moradabad is a district of Uttar Pradesh');
INSERT INTO districts VALUES('M650','Muzaffarnagar','UP26','Muzaffarnagar is a district of Uttar Pradesh');
INSERT INTO districts VALUES('P651','Pilibhit','UP26','Pilibhit is a district of Uttar Pradesh');
INSERT INTO districts VALUES('P652','Pratapgarh','UP26','Pratapgarh is a district of Uttar Pradesh');
INSERT INTO districts VALUES('R653','Raebareli','UP26','Raebareli is a district of Uttar Pradesh');
INSERT INTO districts VALUES('R654','Rampur','UP26','Rampur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('S655','Saharanpur','UP26','Saharanpur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('S656','Sambhal','UP26','Sambhal is a district of Uttar Pradesh');
INSERT INTO districts VALUES('SKN657','Sant Kabir Nagar','UP26','Sant Kabir Nagar is a district of Uttar Pradesh');
INSERT INTO districts VALUES('S658','Shahjahanpur','UP26','Shahjahanpur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('S659','Shamli','UP26','Shamli is a district of Uttar Pradesh');
INSERT INTO districts VALUES('S660','Shravasti','UP26','Shravasti is a district of Uttar Pradesh');
INSERT INTO districts VALUES('S661','Siddharthnagar','UP26','Siddharthnagar is a district of Uttar Pradesh');
INSERT INTO districts VALUES('S662','Sitapur','UP26','Sitapur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('S663','Sonbhadra','UP26','Sonbhadra is a district of Uttar Pradesh');
INSERT INTO districts VALUES('S664','Sultanpur','UP26','Sultanpur is a district of Uttar Pradesh');
INSERT INTO districts VALUES('U665','Unnao','UP26','Unnao is a district of Uttar Pradesh');
INSERT INTO districts VALUES('V666','Varanasi','UP26','Varanasi is a district of Uttar Pradesh');
INSERT INTO districts VALUES('A667','Almora','U27','Almora is a district of Uttarakhand');
INSERT INTO districts VALUES('B668','Bageshwar','U27','Bageshwar is a district of Uttarakhand');
INSERT INTO districts VALUES('C669','Chamoli','U27','Chamoli is a district of Uttarakhand');
INSERT INTO districts VALUES('C670','Champawat','U27','Champawat is a district of Uttarakhand');
INSERT INTO districts VALUES('D671','Dehradun','U27','Dehradun is a district of Uttarakhand');
INSERT INTO districts VALUES('H672','Haridwar','U27','Haridwar is a district of Uttarakhand');
INSERT INTO districts VALUES('N673','Nainital','U27','Nainital is a district of Uttarakhand');
INSERT INTO districts VALUES('P674','Pauri','U27','Pauri is a district of Uttarakhand');
INSERT INTO districts VALUES('P675','Pithoragarh','U27','Pithoragarh is a district of Uttarakhand');
INSERT INTO districts VALUES('R676','Rudraprayag','U27','Rudraprayag is a district of Uttarakhand');
INSERT INTO districts VALUES('T677','Tehri','U27','Tehri is a district of Uttarakhand');
INSERT INTO districts VALUES('USN678','Udham Singh Nagar','U27','Udham Singh Nagar is a district of Uttarakhand');
INSERT INTO districts VALUES('U679','Uttarkashi','U27','Uttarkashi is a district of Uttarakhand');
INSERT INTO districts VALUES('A680','Alipurduar','WB28','Alipurduar is a district of West Bengal');
INSERT INTO districts VALUES('B681','Bankura','WB28','Bankura is a district of West Bengal');
INSERT INTO districts VALUES('B682','Birbhum','WB28','Birbhum is a district of West Bengal');
INSERT INTO districts VALUES('CB683','Cooch Behar','WB28','Cooch Behar is a district of West Bengal');
INSERT INTO districts VALUES('DD684','Dakshin Dinajpur','WB28','Dakshin Dinajpur is a district of West Bengal');
INSERT INTO districts VALUES('D685','Darjeeling','WB28','Darjeeling is a district of West Bengal');
INSERT INTO districts VALUES('H686','Hooghly','WB28','Hooghly is a district of West Bengal');
INSERT INTO districts VALUES('H687','Howrah','WB28','Howrah is a district of West Bengal');
INSERT INTO districts VALUES('J688','Jalpaiguri','WB28','Jalpaiguri is a district of West Bengal');
INSERT INTO districts VALUES('J689','Jhargram','WB28','Jhargram is a district of West Bengal');
INSERT INTO districts VALUES('K690','Kalimpong','WB28','Kalimpong is a district of West Bengal');
INSERT INTO districts VALUES('K691','Kolkata','WB28','Kolkata is a district of West Bengal');
INSERT INTO districts VALUES('M692','Malda','WB28','Malda is a district of West Bengal');
INSERT INTO districts VALUES('M693','Murshidabad','WB28','Murshidabad is a district of West Bengal');
INSERT INTO districts VALUES('N694','Nadia','WB28','Nadia is a district of West Bengal');
INSERT INTO districts VALUES('NP695','North 24 Parganas','WB28','North 24 Parganas is a district of West Bengal');
INSERT INTO districts VALUES('PM696','Paschim Medinipur','WB28','Paschim Medinipur is a district of West Bengal');
INSERT INTO districts VALUES('B697','Bardhaman','WB28','Bardhaman is a district of West Bengal');
INSERT INTO districts VALUES('PM698','Purba Medinipur','WB28','Purba Medinipur is a district of West Bengal');
INSERT INTO districts VALUES('P699','Purulia','WB28','Purulia is a district of West Bengal');
INSERT INTO districts VALUES('SP700','South 24 Parganas','WB28','South 24 Parganas is a district of West Bengal');
INSERT INTO districts VALUES('UD701','Uttar Dinajpur','WB28','Uttar Dinajpur is a district of West Bengal');
INSERT INTO districts VALUES('N702','Nicobar','AN29','Nicobar is a district of Andaman Nicobar');
INSERT INTO districts VALUES('NMA703','North Middle Andaman','AN29','North Middle Andaman is a district of Andaman Nicobar');
INSERT INTO districts VALUES('SA704','South Andaman','AN29','South Andaman is a district of Andaman Nicobar');
INSERT INTO districts VALUES('C705','Chandigarh','C30','Chandigarh is a district of Chandigarh');
INSERT INTO districts VALUES('DNH706','Dadra Nagar Haveli','DH31','Dadra Nagar Haveli is a district of Dadra Haveli');
INSERT INTO districts VALUES('D707','Daman','DD32','Daman is a district of Daman Diu');
INSERT INTO districts VALUES('D708','Diu','DD32','Diu is a district of Daman Diu');
INSERT INTO districts VALUES('CD709','Central Delhi','D33','Central Delhi is a district of Delhi');
INSERT INTO districts VALUES('ED710','East Delhi','D33','East Delhi is a district of Delhi');
INSERT INTO districts VALUES('ND711','New Delhi','D33','New Delhi is a district of Delhi');
INSERT INTO districts VALUES('ND712','North Delhi','D33','North Delhi is a district of Delhi');
INSERT INTO districts VALUES('NED713','North East Delhi','D33','North East Delhi is a district of Delhi');
INSERT INTO districts VALUES('NWD714','North West Delhi','D33','North West Delhi is a district of Delhi');
INSERT INTO districts VALUES('S715','Shahdara','D33','Shahdara is a district of Delhi');
INSERT INTO districts VALUES('SD716','South Delhi','D33','South Delhi is a district of Delhi');
INSERT INTO districts VALUES('SED717','South East Delhi','D33','South East Delhi is a district of Delhi');
INSERT INTO districts VALUES('SWD718','South West Delhi','D33','South West Delhi is a district of Delhi');
INSERT INTO districts VALUES('WD719','West Delhi','D33','West Delhi is a district of Delhi');
INSERT INTO districts VALUES('L720','Lakshadweep','L34','Lakshadweep is a district of Lakshadweep');
INSERT INTO districts VALUES('K721','Karaikal','P35','Karaikal is a district of Puducherry');
INSERT INTO districts VALUES('M722','Mahe','P35','Mahe is a district of Puducherry');
INSERT INTO districts VALUES('P723','Puducherry','P35','Puducherry is a district of Puducherry');
INSERT INTO districts VALUES('Y724','Yanam','P35','Yanam is a district of Puducherry');
