CREATE TABLE questions(
    no INT NOT NULL AUTO_INCREMENT,
    question VARCHAR(100) NOT NULL,
    optionA VARCHAR(50) NOT NULL,
    optionB VARCHAR(50) NOT NULL,
    optionC VARCHAR(50) NOT NULL,
    optionD VARCHAR(50) NOT NULL,
    answer VARCHAR(50) NOT NULL,
    PRIMARY KEY (no)
);