INSERT INTO states VALUES('AP0','Andra Pradesh');
INSERT INTO states VALUES('AP1','Arunachal Pradesh');
INSERT INTO states VALUES('A2','Assam');
INSERT INTO states VALUES('B3','Bihar');
INSERT INTO states VALUES('C4','Chhattisgarh');
INSERT INTO states VALUES('G5','Goa');
INSERT INTO states VALUES('G6','Gujarat');
INSERT INTO states VALUES('H7','Haryana');
INSERT INTO states VALUES('HP8','Himachal Pradesh');
INSERT INTO states VALUES('JK9','Jammu Kashmir');
INSERT INTO states VALUES('J10','Jharkhand');
INSERT INTO states VALUES('K11','Karnataka');
INSERT INTO states VALUES('K12','Kerala');
INSERT INTO states VALUES('MP13','Madhya Pradesh');
INSERT INTO states VALUES('M14','Maharashtra');
INSERT INTO states VALUES('M15','Manipur');
INSERT INTO states VALUES('M16','Meghalaya');
INSERT INTO states VALUES('M17','Mizoram');
INSERT INTO states VALUES('N18','Nagaland');
INSERT INTO states VALUES('O19','Odisha');
INSERT INTO states VALUES('P20','Punjab');
INSERT INTO states VALUES('R21','Rajasthan');
INSERT INTO states VALUES('S22','Sikkim');
INSERT INTO states VALUES('TN23','Tamil Nadu');
INSERT INTO states VALUES('T24','Telangana');
INSERT INTO states VALUES('T25','Tripura');
INSERT INTO states VALUES('UP26','Uttar Pradesh');
INSERT INTO states VALUES('U27','Uttarakhand');
INSERT INTO states VALUES('WB28','West Bengal');
INSERT INTO states VALUES('AN29','Andaman Nicobar');
INSERT INTO states VALUES('C30','Chandigarh');
INSERT INTO states VALUES('DH31','Dadra Haveli');
INSERT INTO states VALUES('DD32','Daman Diu');
INSERT INTO states VALUES('D33','Delhi');
INSERT INTO states VALUES('L34','Lakshadweep');
INSERT INTO states VALUES('P35','Puducherry');
